package(default_visibility = ["//visibility:public"])

cc_library(
    name = "factor_graph",
    srcs = [
        "types.hh",
    ],
    deps = [
        "@automaton_common//common",
        "@automaton_common//common:cereal",
    ],
)


