package(default_visibility = ["//visibility:public"])

cc_library(
    name = "factors",
    hdrs = [
        "types.hh",
    ],
    deps = [
        "@automaton_common//common/hash",
        "@symforce_repo//:symforce",
    ],
)
